# Generated by Django 4.1 on 2022-10-23 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='to_do_list_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_quantity', models.IntegerField()),
                ('related_image', models.ImageField(upload_to='')),
                ('task_ststus', models.BooleanField()),
                ('end_date', models.DateTimeField()),
                ('assign_to', models.ManyToManyField(through='to_do_list.list_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='list_member',
            name='to_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.to_do_list_model'),
        ),
        migrations.AddField(
            model_name='list_member',
            name='uni_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
