# Generated by Django 4.1 on 2022-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list_models',
            name='related_image',
            field=models.ImageField(blank=True, upload_to='media/related_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profile_images/'),
        ),
    ]
