# Generated by Django 4.1 on 2022-10-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_list_member_to_do_list_model_list_member_to_do_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list_model',
            name='assign_to',
        ),
    ]
