# Generated by Django 4.1 on 2022-10-23 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_to_do_list_model_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list_model',
            name='assign_to',
            field=models.ManyToManyField(through='to_do_list.list_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
