# Generated by Django 4.1 on 2022-10-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_to_do_list_model_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list_model',
            name='related_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
