# Generated by Django 4.1 on 2022-10-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_alter_to_do_list_model_related_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_list_model',
            old_name='task_ststus',
            new_name='task_status',
        ),
    ]
