# Generated by Django 4.1 on 2022-10-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields_try', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diff_field',
            name='Inage',
        ),
        migrations.AddField(
            model_name='diff_field',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
